import type { Game } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// Mock game catalog. All titles fictional to avoid trademark issues.
// traditionalSizeMB is calibrated to real-world AAA benchmarks (50-130 GB).
// bootstrapSizeMB is ~0.25-0.35% of traditional — the pitch's core claim.
// ─────────────────────────────────────────────────────────────────────────────

export const GAMES: Game[] = [
  {
    id: "ironveil",
    title: "Ironveil: Last Bastion",
    tagline: "Hold the final citadel against the Ash Legion.",
    genre: "Action RPG",
    tier: "Premium",
    traditionalSizeMB: 82_000,
    bootstrapSizeMB: 220,
    traditionalInstallMinutes: 45,
    bootstrapInstallSeconds: 8,
    coverGradient: ["#7F1D1D", "#F59E0B"],
    zones: ["Citadel Courtyard", "Ashfall Keep", "The Scorched Vault", "Ember Spire"],
  },
  {
    id: "aetheria",
    title: "Chronicles of Aetheria",
    tagline: "An open-world saga five generations in the making.",
    genre: "Open World",
    tier: "Premium",
    traditionalSizeMB: 115_000,
    bootstrapSizeMB: 310,
    traditionalInstallMinutes: 62,
    bootstrapInstallSeconds: 9,
    coverGradient: ["#1E3A8A", "#22D3EE"],
    zones: ["Silverreach Plains", "Mistwood Hollow", "Crystal Caverns", "Highspire Capital"],
  },
  {
    id: "neonraid",
    title: "Neon Raid 2088",
    tagline: "High-frequency combat in a vertical megacity.",
    genre: "Shooter",
    tier: "Premium",
    traditionalSizeMB: 68_000,
    bootstrapSizeMB: 180,
    traditionalInstallMinutes: 38,
    bootstrapInstallSeconds: 7,
    coverGradient: ["#581C87", "#EC4899"],
    zones: ["Sector 7 Rooftops", "Kowloon Undercity", "The Stacks", "Neon Expressway"],
  },
  {
    id: "stormforge",
    title: "Stormforge Arena",
    tagline: "5v5 MOBA with mechanised champions.",
    genre: "MOBA",
    tier: "Basic",
    traditionalSizeMB: 45_000,
    bootstrapSizeMB: 140,
    traditionalInstallMinutes: 25,
    bootstrapInstallSeconds: 6,
    coverGradient: ["#0F766E", "#FBBF24"],
    zones: ["Summoner's Rift", "Dragon Pit", "Baron's Lair", "Nexus Core"],
  },
  {
    id: "valdora",
    title: "Echoes of Valdora",
    tagline: "A living fantasy MMO with millions of stories.",
    genre: "MMO",
    tier: "Premium",
    traditionalSizeMB: 128_000,
    bootstrapSizeMB: 380,
    traditionalInstallMinutes: 70,
    bootstrapInstallSeconds: 10,
    coverGradient: ["#064E3B", "#A7F3D0"],
    zones: ["Stormhaven Harbor", "Whispering Woods", "Dragonspine Peaks", "The Sunken Empire"],
  },
  {
    id: "crimson",
    title: "Crimson Tactics",
    tagline: "Turn-based warfare on a grand strategic scale.",
    genre: "Strategy",
    tier: "Basic",
    traditionalSizeMB: 32_000,
    bootstrapSizeMB: 95,
    traditionalInstallMinutes: 18,
    bootstrapInstallSeconds: 5,
    coverGradient: ["#7C2D12", "#FCD34D"],
    zones: ["Command Bridge", "Eastern Front", "Forward Outpost", "Capital Siege"],
  },
  {
    id: "voidrunner",
    title: "Voidrunner",
    tagline: "Charter your own path through a living galaxy.",
    genre: "Space Sim",
    tier: "Premium",
    traditionalSizeMB: 74_000,
    bootstrapSizeMB: 210,
    traditionalInstallMinutes: 40,
    bootstrapInstallSeconds: 8,
    coverGradient: ["#1E1B4B", "#60A5FA"],
    zones: ["Sol Station", "Ceres Belt", "The Kuiper Shadow", "Titan's Edge"],
  },
  {
    id: "ashenfold",
    title: "Ashenfold",
    tagline: "Survive one more night in the quarantine zone.",
    genre: "Survival Horror",
    tier: "Basic",
    traditionalSizeMB: 58_000,
    bootstrapSizeMB: 165,
    traditionalInstallMinutes: 32,
    bootstrapInstallSeconds: 7,
    coverGradient: ["#18181B", "#991B1B"],
    zones: ["Abandoned Hospital", "Subway Tunnels", "Safe House", "The Broadcast Tower"],
  },
  {
    id: "skybound",
    title: "Skybound Legion",
    tagline: "Co-op sky piracy for up to four friends.",
    genre: "Co-op Adventure",
    tier: "Premium",
    traditionalSizeMB: 92_000,
    bootstrapSizeMB: 260,
    traditionalInstallMinutes: 51,
    bootstrapInstallSeconds: 8,
    coverGradient: ["#0C4A6E", "#FDE68A"],
    zones: ["Skyport Aurelia", "Cloud Reef", "The Storm Corridor", "Sunken Airship"],
  },
  {
    id: "grandmaster",
    title: "Grandmaster Chess Universe",
    tagline: "Study, train, and compete with a world of players.",
    genre: "Simulation",
    tier: "Basic",
    traditionalSizeMB: 12_000,
    bootstrapSizeMB: 40,
    traditionalInstallMinutes: 8,
    bootstrapInstallSeconds: 4,
    coverGradient: ["#1F2937", "#E5E7EB"],
    zones: ["Opening Theory", "Middlegame Lab", "Endgame Studio", "Tournament Hall"],
  },
  {
    id: "ryudo",
    title: "Ryudo: Bladefall",
    tagline: "Honor, steel, and an ancient enemy awakened.",
    genre: "Fighting",
    tier: "Premium",
    traditionalSizeMB: 86_000,
    bootstrapSizeMB: 240,
    traditionalInstallMinutes: 48,
    bootstrapInstallSeconds: 8,
    coverGradient: ["#450A0A", "#F97316"],
    zones: ["Mountain Shrine", "Bamboo Grove", "The Daimyo's Court", "Crimson Battlefield"],
  },
  {
    id: "frostbite",
    title: "Frostbite Expedition",
    tagline: "Every degree below zero is another decision.",
    genre: "Survival",
    tier: "Basic",
    traditionalSizeMB: 51_000,
    bootstrapSizeMB: 150,
    traditionalInstallMinutes: 28,
    bootstrapInstallSeconds: 6,
    coverGradient: ["#0C4A6E", "#BAE6FD"],
    zones: ["Base Camp", "Glacier Approach", "Hidden Crevasse", "The Summit"],
  },
];

export function getGameById(id: string): Game | undefined {
  return GAMES.find((g) => g.id === id);
}

// Human-readable size formatter (MB → GB if ≥ 1024)
export function formatSize(sizeMB: number): string {
  if (sizeMB >= 1024) return `${(sizeMB / 1024).toFixed(1)} GB`;
  return `${sizeMB.toFixed(0)} MB`;
}
